let homediv = document.getElementById('homecontainer')
let educationdiv = document.getElementById('educationcontainer')
let skillsdiv = document.getElementById('skillscontainer')
let projectsdiv = document.getElementById('projectcontainer')
let contactdiv = document.getElementById('contactcontainer')
homediv.style.display='none'
educationdiv.style.display='none'
skillsdiv.style.display='none'
projectsdiv.style.display='none'
contactdiv.style.display='none'